-- SQL commands to create the missing tables in your Supabase project

-- 1. Create the `claims` table
CREATE TABLE public.claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip TEXT NOT NULL,
  tiktok_url TEXT NOT NULL,
  likes_count INTEGER DEFAULT 30,
  claimed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  status TEXT DEFAULT 'pending'
);

-- 2. Create the `config` table
CREATE TABLE public.config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Insert default config for max_likes
INSERT INTO public.config (key, value) VALUES ('max_likes', '30');

-- 3. Create the `page_loads` table
CREATE TABLE public.page_loads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip TEXT NOT NULL,
  token TEXT NOT NULL UNIQUE,
  loaded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
