[package]
name = "devleoleo-ops/minnaaa"
version = "0.2.0"
description = "TikTok Free Likes - Next.js"

[dependencies]
"wasmer/winterjs" = "^1.2.0"

[fs]
".next/standalone" = ".next/standalone"
".next/static" = ".next/standalone/.next/static"
"public" = ".next/standalone/public"

[[command]]
name = "start"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = [".next/standalone/server.js"]
